### ISSUE TITLE
Can not register a PoP [Code : 422]

### ISSUE THREAD

**Issue by omeshF** [openbaton/openstack-plugin#18]
I am using the latest NFVO and trying to upload a PoP with the following json 
```
{
  "name":"vim-instance",
  "authUrl":"http://192.168.174.136:5000/v2.0",
  "tenant":"tenant-name",
  "username":"userName",
  "password":"password",
  "keyPair":"keyName",
  "securityGroups": [
    "securityName"
  ],
  "type":"openstack4j",
  "location":{
    "name":"Berlin",
    "latitude":"52.525876",
    "longitude":"13.314400"
  }
}
```

**I receive the following error.** 

> org.openbaton.exceptions.PluginException: Error instantiating plugin: no plugin found with name: vim-drivers.openstack4j. into queues: [nfvo.event.register, nfvo.event.unregister, nfvo.manager.handling, vim-drivers.openstack.openstack, vim-drivers.test.test, vnfm.nfvo.actions, vnfm.nfvo.actions.reply] Code: 422

Following is a log from openstack plugin log

LF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/openbaton/plugins/vim-drivers/openbaton-plugin-vimdriver-openstack-4j-5.2.0.jar!/lib/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/openbaton/plugins/vim-drivers/openbaton-plugin-vimdriver-openstack-4j-5.2.0.jar!/lib/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
2018-05-02 14:23:31:345 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:346 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$
2018-05-02 14:23:31:347 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:347 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$
2018-05-02 14:23:31:348 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:348 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$
2018-05-02 14:23:31:361 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:362 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$
2018-05-02 14:23:31:368 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:368 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$
2018-05-02 14:23:31:370 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:370 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$
2018-05-02 14:23:31:372 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:373 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$
2018-05-02 14:23:31:375 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:375 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$
2018-05-02 14:23:31:376 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:376 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$
2018-05-02 14:23:31:379 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-05-02 14:23:31:379 +0100 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properti$

Please help. Thank you in advance

**Comment by n1kos87** [comment]
I have tha same problem, I am using the latest version of NFVO and tha latest version of openstack plugin which I choose during the bootstrap installation on a Ubuntu Server 16.04.4 VM

Following is the logs from the Openstack Plugin:

`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/openbaton/plugins/vim-drivers/openbaton-plugin-vimdriver-openstack-4j-5.2.0.jar!/lib/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/openbaton/plugins/vim-drivers/openbaton-plugin-vimdriver-openstack-4j-5.2.0.jar!/lib/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
2018-04-03 13:00:58:855 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:857 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:00:58:879 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:879 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:00:58:895 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:895 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:00:58:899 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:899 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:00:58:956 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:956 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:00:58:961 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:961 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:00:58:971 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:971 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:00:58:972 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:973 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:00:58:974 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:974 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:00:58:976 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - external-properties-file: /etc/openbaton/plugin/openstack/driver.properties doesn't exist
2018-04-03 13:00:58:976 +0000 [main] DEBUG org.openbaton.drivers.openstack4j.OpenStack4JDriver - Properties are {connection-timeout=10000, external-properties-file=/etc/openbaton/plugin/openstack/driver.properties, type=openstack, disable-ssl-certificate-checks=true, wait-for-vm=5000, dns-nameserver=8.8.8.8, deallocate-floating-ip=true}
2018-04-03 13:08:35:952 +0000 [pool-1-thread-1] INFO org.openbaton.drivers.openstack4j.OpenStack4JDriver - Refreshing vim instance: Meson
2018-04-03 13:08:38:437 +0000 [pool-25-thread-2] ERROR org.openbaton.drivers.openstack4j.OpenStack4JDriver - RESTEASY004655: Unable to invoke request
ConnectionException{message=RESTEASY004655: Unable to invoke request, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:57)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:31)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:126)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:56)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:118)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:80)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.authenticate(OpenStack4JDriver.java:175)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.listNetworks(OpenStack4JDriver.java:787)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.lambda$refresh$14(OpenStack4JDriver.java:940)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:316)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:462)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:71)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:62)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:55)
	... 12 more
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:312)
	... 16 more
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 19 more
Exception in thread "pool-25-thread-4" Exception in thread "pool-25-thread-5" ConnectionException{message=RESTEASY004655: Unable to invoke request, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:57)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:31)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:126)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:56)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:118)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:80)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.authenticate(OpenStack4JDriver.java:175)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.listKeys(OpenStack4JDriver.java:642)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.lambda$refresh$17(OpenStack4JDriver.java:986)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:316)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:462)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:71)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:62)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:55)
	... 12 more
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:312)
	... 16 more
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 19 more
2018-04-03 13:08:38:439 +0000 [pool-25-thread-1] ERROR org.openbaton.drivers.openstack4j.OpenStack4JDriver - RESTEASY004655: Unable to invoke request
ConnectionException{message=RESTEASY004655: Unable to invoke request, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:57)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:31)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:126)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:56)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:118)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:80)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.authenticate(OpenStack4JDriver.java:175)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.listImages(OpenStack4JDriver.java:668)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.lambda$refresh$13(OpenStack4JDriver.java:925)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:316)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:462)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:71)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:62)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:55)
	... 12 more
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:312)
	... 16 more
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 19 more
2018-04-03 13:08:38:438 +0000 [pool-25-thread-3] ERROR org.openbaton.drivers.openstack4j.OpenStack4JDriver - RESTEASY004655: Unable to invoke request
ConnectionException{message=RESTEASY004655: Unable to invoke request, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:57)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:31)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:126)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:56)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:118)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:80)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.authenticate(OpenStack4JDriver.java:175)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.listFlavors(OpenStack4JDriver.java:896)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.lambda$refresh$15(OpenStack4JDriver.java:956)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:316)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:462)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:71)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:62)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:55)
	... 12 more
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:312)
	... 16 more
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 19 more
ConnectionException{message=RESTEASY004655: Unable to invoke request, status=0}
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:57)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:31)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:126)
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:56)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:118)
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:80)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.authenticate(OpenStack4JDriver.java:175)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.listAvailabilityZone(OpenStack4JDriver.java:1017)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.lambda$refresh$16(OpenStack4JDriver.java:971)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:316)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:462)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:71)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:62)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:55)
	... 12 more
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:312)
	... 16 more
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 19 more
org.openbaton.exceptions.VimDriverException: Error refreshing vim
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.refresh(OpenStack4JDriver.java:1008)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openbaton.plugin.PluginListener.executeMethod(PluginListener.java:266)
	at org.openbaton.plugin.PluginListener.access$400(PluginListener.java:46)
	at org.openbaton.plugin.PluginListener$1.lambda$handleDelivery$0(PluginListener.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbaton.exceptions.VimDriverException: RESTEASY004655: Unable to invoke request
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.listImages(OpenStack4JDriver.java:756)
	at org.openbaton.drivers.openstack4j.OpenStack4JDriver.lambda$refresh$13(OpenStack4JDriver.java:925)
	... 3 more

Thank you in advance
Nick`

**Comment by mzanella** [comment]
Hi!
I have the same problem too using [docker with minimal setup](https://github.com/openbaton/bootstrap/blob/f9d8ad8a1b25e95baae15da7612f2032bfcff20e/distributions/docker/compose/min_nomysql-compose.yml), loading the same JSON.

On openbaton GUI the error was:
![image](https://user-images.githubusercontent.com/12596262/41036321-f64489ee-698f-11e8-9b76-c622e2b995ea.png)

Instead in the terminal:
```
nfvo_1                           | 2018-06-06 11:37:24.991 ERROR 1 --- [nio-8080-exec-5] o.o.n.a.e.GlobalExceptionHandler         : Exception was thrown -> Return message: org.openbaton.exceptions.PluginException: Error instantiating plugin: Connect to localhost:15672 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
```

**Comment by n1kos87** [comment]
Hi,

In my case the probles was that the system administratos closed all the
incoming traffic to the VM that the controller is installed,
I put tha appropriate rules and after this I managed to register the PoP.

But I m not using docker setup




2018-06-06 14:48 GMT+03:00 mzanella <notifications@github.com>:

**Comment by gatici** [comment]
Hello, 

org.openbaton.exceptions.VimException: Vim instance Not refreshed default. Caused by: org.openbaton.exceptions.VimDriverException: Error refreshing vim: Listing images of VIM default (null) threw exceptions using Glance v2: "RESTEASY004655: Unable to invoke request" and using Glance v1: "RESTEASY004655: Unable to invoke request" Code: 422

Does  this  problem solved ? If does,  how  can we solve  it ?

**Comment by sanketgupta99** [comment]
How can I get the openstack plugin logs?
